
import os

PRE_TRAINED_MODEL_NAME="bert-base-uncased"
DROPOUT_RATE=0.0
N_CLASSES=2
LEARNING_RATE=0.00002 * 0.1
EPOCHS=10
N_PARTS=3
MAX_LENGTH=32
TRUNCATION=True
ADD_SPECIAL_TOKENS=True
RETURN_TOKEN_TYPE_IDS=False
PAD_TO_MAX_LENGTH=True
RETURN_ATTENTION_MASK=True
RETURN_TENSORS="pt"
NEW_MODEL_NAME=os.getcwd() + "/src/bert_model/generated_models/model_{}.pt"
N_SUBSET=None
PRED_BATCH_SIZE=128
TEXT_COLUMN="text"
LABEL_COLUMN="target"
N_PREDICTIONS=None
SEED=1